### ISSUE TITLE
npm run dev:chrome出錯

### ISSUE THREAD

**Issue by mrbigmouth** [abalone0204/Clairvoyance#21]
cp的指令是不是下錯了？
環境是Mac。（mac的cp指令有比較不一樣!?）

？？？:Clairvoyance ？？？$ npm run dev:chrome

> clairvoyance@1.0.0 dev:chrome /Users/？？？/Documents/Clairvoyance
> npm run clean && webpack && npm run migrate:chrome

> clairvoyance@1.0.0 clean /Users/？？？/Documents/Clairvoyance
> rm -f dist/*.js dist/*.js.map chromeExtension/dist/*

Hash: 426615ebcac3cf0397aa
Version: webpack 1.13.1
Time: 12179ms
                                 Asset     Size  Chunks             Chunk Names
                   eventPage-bundle.js  38.9 kB       2  [emitted]  eventPage
  25a32416abee198dd821b0b17a198a8f.eot  76.5 kB          [emitted]  
 c8ddf1e5e5bf3682bc7bebf30f394148.woff  90.4 kB          [emitted]  
  1dc35d25e61d819a9c357074014867ab.ttf   153 kB          [emitted]  
  d7c639084f684d66a1bc66855d193ed8.svg   392 kB          [emitted]  
                     content-bundle.js  1.67 MB       0  [emitted]  content
                         dev-bundle.js  1.79 MB       1  [emitted]  dev
e6cf7c6ec7c2d6f670ae9d762604cb0b.woff2  71.9 kB          [emitted]  
                     options-bundle.js  1.47 MB       3  [emitted]  options
                       popup-bundle.js   779 kB       4  [emitted]  popup
                 content-bundle.js.map  1.99 MB       0  [emitted]  content
                     dev-bundle.js.map  2.16 MB       1  [emitted]  dev
               eventPage-bundle.js.map  44.5 kB       2  [emitted]  eventPage
                 options-bundle.js.map  1.77 MB       3  [emitted]  options
                   popup-bundle.js.map   915 kB       4  [emitted]  popup
   [0] multi dev 52 bytes {1} [built]
    + 988 hidden modules

> clairvoyance@1.0.0 migrate:chrome /Users/？？？/Documents/Clairvoyance
> cp dist/* chromeExtension/dist

usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "migrate:chrome"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! clairvoyance@1.0.0 migrate:chrome: `cp dist/* chromeExtension/dist`
npm ERR! Exit status 64
npm ERR! 
npm ERR! Failed at the clairvoyance@1.0.0 migrate:chrome script 'cp dist/* chromeExtension/dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the clairvoyance package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cp dist/* chromeExtension/dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs clairvoyance
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls clairvoyance
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/？？？/Documents/Clairvoyance/npm-debug.log

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev:chrome"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! clairvoyance@1.0.0 dev:chrome: `npm run clean && webpack && npm run migrate:chrome`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the clairvoyance@1.0.0 dev:chrome script 'npm run clean && webpack && npm run migrate:chrome'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the clairvoyance package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && webpack && npm run migrate:chrome
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs clairvoyance
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls clairvoyance
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/？？？/Documents/Clairvoyance/npm-debug.log
？？？:Clairvoyance ？？？$

**Comment by mrbigmouth** [comment]
我把package.json的scripts改成 {
//....略
    "migrate:chrome": "cp -R dist chromeExtension/dist",
//....略
}
就好了

**Comment by abalone0204** [comment]
這樣子貌似會變成 `chromeExtension/dist/dist`，

應該要變成 `cp -R dist chromeExtension` 才對。

我剛剛更新了，你 pull 之後再試看看。

**Comment by mrbigmouth** [comment]
沒問題了
