### ISSUE TITLE
是否能夠正常留言？

### ISSUE THREAD

**Issue by zeroade** [abalone0204/Clairvoyance#22]
目前在某個工作下留言或評價後，在refresh一次，發覺還是看不到該留言?

**Comment by abalone0204** [comment]
有沒有連結可以給我呢？

**Comment by zeroade** [comment]
http://www.104.com.tw/job/?jobno=3l5jx&jobsource=n104bank1 這個可以嗎?

**Comment by abalone0204** [comment]
這個解掉了，

把插件升到 2.0  版本之後，應當就不會遇到這個問題。

**Comment by abalone0204** [comment]
@zeroade 我把 Issue 名字做了更改，
未來如果遇到無法留言的問題，都會在這個 Issue 下方討論，
就不另外開票解決了！

**Comment by eecarnegie** [comment]
您好，我這個連結也不能留言，可以幫忙確認下嗎？謝謝。
http://goo.gl/r8sxEJ

**Comment by zeroade** [comment]
我這邊更版後已可正常運作

**Comment by eecarnegie** [comment]
更新後已ok，謝謝。

**Comment by abalone0204** [comment]
暫時先關閉，等到有出現無法留言情形時再打開
