### ISSUE TITLE
Android版本

### ISSUE THREAD

**Issue by iyotetsuya** [abalone0204/Clairvoyance#30]
開這個issues只是當個提醒，
個人有Android開發能力，
有需要的話願意貢獻一下心力。

功能的話…
如果擔心data不夠多的話，
可以反向讓使用者用關鍵字去撈職缺已有留言的部份，
再開WebView顯示人力銀行的頁面，
這樣可以從己有資料的部份當起頭。

**Comment by abalone0204** [comment]
我也在想應該用怎樣的方式把資料的 API 弄出來 XD

不過就如 FAQ 中說的，現在還沒有跨到其他平台的那一步。

這個 Issue 會開著，等到 Clairvoyance 準備好的那一天 。

**Comment by nelsonchung** [comment]
這就是開源精神
Fighting

**Comment by mrjerometw** [comment]
您好, 我這邊也可以幫忙協助Android/ios的開發

讓我們一起打造台灣更好的勞方環境!

**Comment by mrjerometw** [comment]
您好, 我這邊也可以協助開發android/ios, 

讓我們一起改善的勞方資方資訊不平等的環境吧!

**Comment by Ayukawayen** [comment]
正在做一個*這三小*的APP
[![](http://i.imgur.com/UiycRN8.jpg)](https://drive.google.com/file/d/0Bw-fynTrrsH3dng0Tm5vNS1EMjg/view)

功能就是從瀏覽器接收網頁分享再叫瀏覽器開網頁*(這三小)*，完全依附在其他APP上。
不要說Webview了，除了Loading畫面外基本上沒有自己的View，一個java檔就可以寫完的APP。 XD

**Comment by Ayukawayen** [comment]
不好意思想請教Denny的意見，我想開發天眼通的Android APP(如前篇所述)，APP的package name該怎麼取好?
如果取com.github.clairvoyance怕佔用官方版的名字。用自己的domain又似乎不太尊重。

**Comment by iyotetsuya** [comment]
有open source的話，我認為使用相同網域是比較適合的

**Comment by iyotetsuya** [comment]
我還沒有做很多研究，
如果是用disqus來做留言的話
https://disqus.com/home/forums/clv-bakc-end/
應該可以直接用它們的API取資料
https://disqus.com/api/docs/cursors/
我周末會來試試。

**Comment by abalone0204** [comment]
@Ayukawayen 
Android App 的話，我仍然覺得現階段還不急著做，
而且這個使用行為有一點點反人類啊 XDDD
未來我會使用這個 Domain 去開發 App，但功能可能就跟插件的不太一樣。
所以如果你想玩玩的話可以用自己 Domain 沒關係，
記得標注一下原本的 repo 就好了。
（簡單說就是照 MIT license 走啦）
@iyotetsuya  mm 其實我這邊已經有 parse 好的 json 檔了 XDD
而且之後沒有要用 Disqus 了，等公司評論開發完再來討論 App 的事情也不遲。

至於評論的 API 我記得另個 Issue 也有要做類似的事情，
我還在想這 API 要用怎樣的形式開放，總之不要重工會比較好。
最近專案比較忙，
而且 github 的 notifications 太容易被忽略，我看晚點來開個 slack 好了 QQ

**Comment by Ayukawayen** [comment]
操作流程習慣就好。希望啦 XD
就想說快速做一個讓使用者能在手機上看到天眼通評論的APP出來。
不過我不曉得有多少人會用手機看104網頁......

之後不用Disqus，這招就沒用啦，除非生出另外的留言網頁來連。 XD

**Comment by abalone0204** [comment]
做完記得丟出來給大家玩玩呀XD

**Comment by Ayukawayen** [comment]
https://play.google.com/apps/testing/net.ayukawayen.clairvoyance
放到Play上Open Beta了，加入測試人員就可以安裝囉。

Demo: [![](http://i.imgur.com/UiycRN8.jpg)](https://drive.google.com/open?id=0Bw-fynTrrsH3bVZIMkR0dUJWbkE)

Source Code也上傳了，放在同repo的另一個branch下:
- [Source Code](https://github.com/Ayukawayen/Clairvoyance/tree/feature/android/android)
- [備忘事項](https://github.com/Ayukawayen/Clairvoyance/commit/ae5356763f33f088dd5c1a84c190d418a9dd23b1#commitcomment-18041982)
