### ISSUE TITLE
Chrome web store 輸入 "Clairvoyance" "求職天眼通" 都找不到

### ISSUE THREAD

**Issue by camiyu917** [abalone0204/Clairvoyance#38]
Chrome web store 輸入 "Clairvoyance" "求職天眼通" 都找不到耶, 
但是在 Google 搜尋就找的到了...

**Comment by abalone0204** [comment]
因為目前還在處理被攻擊的東西，
所以我先把它改成不公開的，
待會修好以後就會再度公開了 :D。
