### ISSUE TITLE
請問為什麼需讀取瀏覽紀錄?

### ISSUE THREAD

**Issue by BeeHuang** [abalone0204/Clairvoyance#39]
作者前輩你好
  今天更新跟我要權限, 看上面104 1111感覺都很正常.
但下面卻要求瀏覽紀錄, 感覺蠻奇怪的, 所以來詢問.

  請問為什麼需讀取瀏覽紀錄?
這樣對一般使用者 會感覺不好?
如果認同的話, 請問能增加什麼相對應說明嗎? 或者怎麼解決呢?~
謝謝
<img width="445" alt="2016-06-17 11 37 57" src="https://cloud.githubusercontent.com/assets/5171053/16156011/ad5ed824-34e4-11e6-8915-4107e30526cd.png">

**Comment by abalone0204** [comment]
因為之前在 Facebook Oauth 登入時，
需要重新開一個分頁，permission 中要加上 `tabs` 和 `activeTab` 這兩個 permissions。
你可以到專案中的[manifest.json](https://github.com/abalone0204/Clairvoyance/blob/master/chromeExtension/manifest.json#L22:L27)去觀看。

你可能會覺得很奇怪，tab 跟瀏覽紀錄有什麼關係，
事實上就是沒什麼關係，但是 google 團隊翻譯出來的結果就是這樣，
可以看一下 google chrome extension 的文件，
裡面有寫到 tabs 跟 activeTab 在做什麼：

- [Declare permissions](https://developer.chrome.com/extensions/declare_permissions#manifest)

你會明白我一點都沒有想要拿你們瀏覽紀錄的意思。

---

然後這才是真正會拿到瀏覽紀錄的 permission：

- [chrome.history](https://developer.chrome.com/extensions/history)

我的 `manifest.json` 裡面應該沒有任何跟 history 有關。

----

看到現在，
你可能就會理解有時候不是我不想多做解釋，
這中間要解釋的東西有一點太多了。

**Comment by Ayukawayen** [comment]
應該是tabs permission。

然後我剛剛才知道chrome.tabs.create不需要tabs permission....

https://developer.chrome.com/extensions/tabs
> You can use most chrome.tabs methods and events without declaring any permissions in the extension's manifest file. However, if you require access to the url, title, or favIconUrl properties of tabs.Tab, you must declare the "tabs" permission in the manifest

**Comment by BeeHuang** [comment]
謝謝回答!
感恩~

**Comment by abalone0204** [comment]
@Ayukawayen  what the fuck XDDDDDDDDDDDDDD

**Comment by Ayukawayen** [comment]
所以所謂**讀取瀏覽記錄**權限就是可以取得分頁的url, title,還有favIconUrl囉? 好像也不是沒有道理 XD

**Comment by abalone0204** [comment]
經你這樣說我也開始相信了。
但我覺得這翻譯還是會像 @BeeHuang 說的一樣，
讓使用者以為我是拿了 `history` 的 permission
