### ISSUE TITLE
有人做591的留言插件嗎

### ISSUE THREAD

**Issue by luckstar77** [abalone0204/Clairvoyance#40]
Hi 作者

在ptt上看到你寫的文章，對於資訊公開透明深表認同

最近本人有在用591看房子

發現591雖然有留言功能，但是一定要房東或者賣家回答其他人才看的到

並沒有流暢的租客或者買家互相留言討論

尤其是發布者留的資訊常常有所保留，導致資訊不對等

看到這個插件覺得是可以加在591上使雙方有流暢的討論平台，以達到資訊對等

不知作者是否有興趣架在591或者我可以修改後架在591上(一樣採用open source方式)

**Comment by abalone0204** [comment]
Hi ，
其實你可以直接 fork 過去就好 :D 這是 MIT license 的。
不過現在是用 disqus 的方式架設，未來可能還是會切回原本的架構，
到時候可能要留意一下。

我其實租屋上也遇到蠻多麻煩的，也一直在想要怎麼解決這件事情。
這應該不是單純資訊揭露可以解決。
因為房子的所有權就是在房東手上，這個槓桿太大勒。
我未來和幾位朋友也有計劃在這件事情上做些改變，
但現在先專注把這件事做好吧 XD
總之很樂見你將這些 source  code 做其他的應用囉

**Comment by luckstar77** [comment]
看到惡房東的新聞就覺得要有資訊透明的機制

當有人察覺有異，即可做相關查詢討論

避免不知情的人遭受損失

期待你們持續維護!

謝謝你，我先來動工XD
