### ISSUE TITLE
http和https的相同職缺留言不互通

### ISSUE THREAD

**Issue by Ayukawayen** [abalone0204/Clairvoyance#44]
例:
https://www.104.com.tw/job/?jobno=4rxgc&jobsource=pda_b
http://www.104.com.tw/job/?jobno=4rxgc&jobsource=pda_b
http://104.com.tw/job/?jobno=4rxgc&jobsource=pda_b

同一個職缺，https和http的留言不互通，留的言另一邊看不到。
不過同樣是http的話，有www和沒有www的網址，留言倒是可以互通。

應該要做網址標準化連到同一個Thread底下。

**Comment by Ayukawayen** [comment]
querystring不同也不會互通，
例:
https://www.104.com.tw/job/?jobno=4rxgc&jobsource=pda_b
https://www.104.com.tw/job/?jobno=4rxgc
https://www.104.com.tw/job/?jobno=4rxgc&jobsource=104_bank1
https://www.104.com.tw/job/?jobno=4rxgc&jobsource=pda_b&

應該是呼叫disqus API時，t_u這個參數不同的關係吧。

**Comment by Ayukawayen** [comment]
[front-end/app/components/Disqus/index.js](https://github.com/abalone0204/Clairvoyance/blob/2d2f51e41ff22e33aeff272dc1d445885c761115/front-end/app/components/Disqus/index.js)
13: `this.page.url = location.href; // Replace PAGE_URL with your page's canonical URL variable`
應該要放[多重網址的標準網址](https://support.google.com/webmasters/answer/139066?hl=zh-Hant)而不是location.href。

看了網頁原始碼，104和1111都有按規範在`<meta>`裡提供canonical URL，用那個網址當參數應該可以處理這個問題。晚點我試試看。

**Comment by abalone0204** [comment]
Hi，抱歉這兩天事情比較多一點。

我剛剛看了 canonical tag，http 跟 https 是不同的 url。

```
document.querySelector('link[rel="canonical"]').href
```

這個作法可能可以解決另個 issue ，但好像無法完全處理 http 以及 https 的問題。

**Comment by Ayukawayen** [comment]
對喔，與標題不符 XD

一律轉成https應該就行了，沒有違反規範，
雖然和網站宣稱的url的scheme不同，但確實是同一個網頁，應該也不算是不合理使用。

**Comment by Ayukawayen** [comment]
對了，如果這個要改，舊的留言還得要搬過去。

**Comment by abalone0204** [comment]
感謝 @Ayukawayen 啦！
原本的留言我在 disqus 後台想要 url mapper 改過去卻一直給我吃 500 頁面 XD
已經寫信去問他了。

**Comment by Ayukawayen** [comment]
又發現問題了
1111的canonical是http://www.1111.com.tw//job-bank/job-description.asp?eNo=xxx
中間有兩條斜線。

這連得到同一個網頁，但不會match `manifest.json`所設定的條件，所以連過去的網頁上沒有求職小幫手區塊。

再做一個patch改`manifest.json`來解決這問題。

**Comment by abalone0204** [comment]
已解掉
