### ISSUE TITLE
不同管道進入同職缺頁面 留言不互通

### ISSUE THREAD

**Issue by T8TR** [abalone0204/Clairvoyance#45]
直接由該公司職缺列表進入  可見到留言
http://www.1111.com.tw/job-bank/job-description.asp?eNo=55942743

設定搜尋條件後同個職缺  看不見留言
http://www.1111.com.tw/job-bank/job-description.asp?eNo=55942743&agent=home_20160621

謝謝您

**Comment by Ayukawayen** [comment]
我想這和 #44 遇到的是相同的問題。
呼叫API時未使用標準化的網址所造成。

**Comment by abalone0204** [comment]
詳見 #44
